version : "3.8" # we do a little trolling

services:

  flanders:
    build: .
    environment:
      - BOT_TOKEN
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

    depends_on:
      - db

    volumes:
      - ./:/repositories


  db:
    image: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    restart: always


#  miktex:
#    image: miktex/miktex
#
#    volumes:
#      - /miktex
